"""remove service_id extra string

Revision ID: 6be9b5c3b043
Revises: 20260428_0009
Create Date: 2026-05-08 16:16:42.196205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be9b5c3b043'
down_revision: Union[str, None] = '20260428_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop old service_offices table with string-based FK
    op.drop_index('ix_service_offices_id', table_name='service_offices')
    op.drop_index('ix_service_offices_service_id', table_name='service_offices')
    op.drop_index('ix_service_offices_service_name', table_name='service_offices')
    op.drop_table('service_offices')
    
    # Drop FK constraint on service_document_templates BEFORE changing column type
    op.drop_constraint('service_document_templates_service_id_fkey', 'service_document_templates', type_='foreignkey')
    
    # Delete all old records in service_document_templates since they reference old string IDs
    op.execute('DELETE FROM service_document_templates')
    
    # Now convert the column type (will be empty after delete, so cast doesn't matter)
    op.execute('ALTER TABLE service_document_templates ALTER COLUMN service_id TYPE INTEGER USING 0')
    
    # Drop unique constraint and index
    op.drop_constraint('service_document_templates_service_id_key', 'service_document_templates', type_='unique')
    op.drop_index('ix_service_document_templates_service_id', table_name='service_document_templates')
    op.create_index(op.f('ix_service_document_templates_service_id'), 'service_document_templates', ['service_id'], unique=True)
    
    # Recreate FK pointing to services.id (both are now INTEGER)
    op.create_foreign_key('fk_service_document_templates_service_id', 'service_document_templates', 'services', ['service_id'], ['id'], ondelete='CASCADE')
    
    # Now drop the old service_id column from services
    op.drop_index('ix_services_service_id', table_name='services')
    op.drop_constraint('uq_services_service_id', 'services', type_='unique')
    op.drop_column('services', 'service_id')
    
    # Recreate service_offices table with correct structure (numeric service_id)
    op.create_table('service_offices',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('service_name', sa.VARCHAR(length=255), nullable=False),
        sa.Column('service_id', sa.INTEGER(), nullable=False),
        sa.Column('office_name', sa.VARCHAR(length=255), nullable=False),
        sa.Column('address', sa.VARCHAR(length=500), nullable=False),
        sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), nullable=False),
        sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), nullable=False),
        sa.Column('working_hours', sa.VARCHAR(length=255), nullable=False),
        sa.Column('contact_email', sa.VARCHAR(length=255), nullable=False),
        sa.Column('notes', sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='fk_service_offices_service_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='service_offices_pkey')
    )
    op.create_index('ix_service_offices_id', 'service_offices', ['id'], unique=False)
    op.create_index('ix_service_offices_service_id', 'service_offices', ['service_id'], unique=False)
    op.create_index('ix_service_offices_service_name', 'service_offices', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_services_service_id', 'services', ['service_id'])
    op.create_index('ix_services_service_id', 'services', ['service_id'], unique=False)
    op.drop_constraint(None, 'service_document_templates', type_='foreignkey')
    op.create_foreign_key('service_document_templates_service_id_fkey', 'service_document_templates', 'services', ['service_id'], ['service_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_document_templates_service_id'), table_name='service_document_templates')
    op.create_index('ix_service_document_templates_service_id', 'service_document_templates', ['service_id'], unique=False)
    op.create_unique_constraint('service_document_templates_service_id_key', 'service_document_templates', ['service_id'])
    op.alter_column('service_document_templates', 'service_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_table('service_offices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('office_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('working_hours', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name='fk_service_offices_service_id_services', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='service_offices_pkey')
    )
    op.create_index('ix_service_offices_service_name', 'service_offices', ['service_name'], unique=False)
    op.create_index('ix_service_offices_service_id', 'service_offices', ['service_id'], unique=False)
    op.create_index('ix_service_offices_id', 'service_offices', ['id'], unique=False)
    # ### end Alembic commands ###
