"""remove service_id extra string

Revision ID: 6be9b5c3b043
Revises: 20260428_0009
Create Date: 2026-05-08 16:16:42.196205

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be9b5c3b043'
down_revision: Union[str, None] = '20260428_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # First, drop old service_offices table with string-based FK
    op.execute('DROP INDEX IF EXISTS ix_service_offices_id')
    op.execute('DROP INDEX IF EXISTS ix_service_offices_service_id')
    op.execute('DROP INDEX IF EXISTS ix_service_offices_service_name')
    # Drop FK from services that references service_offices before dropping the table
    op.execute('ALTER TABLE services DROP CONSTRAINT IF EXISTS fk_services_service_id_service_offices')
    op.execute('DROP TABLE IF EXISTS service_offices')

    # Handle service_document_templates only if it exists
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'service_document_templates') THEN
                ALTER TABLE service_document_templates DROP CONSTRAINT IF EXISTS service_document_templates_service_id_fkey;
                DELETE FROM service_document_templates;
                ALTER TABLE service_document_templates ALTER COLUMN service_id TYPE INTEGER USING 0;
                ALTER TABLE service_document_templates DROP CONSTRAINT IF EXISTS service_document_templates_service_id_key;
                DROP INDEX IF EXISTS ix_service_document_templates_service_id;
                ALTER TABLE service_document_templates DROP CONSTRAINT IF EXISTS fk_service_document_templates_service_id;
            END IF;
        END
        $$
    """)
    op.execute('DROP INDEX IF EXISTS ix_service_document_templates_service_id')
    op.execute("""
        DO $$
        BEGIN
            IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'service_document_templates') THEN
                CREATE INDEX IF NOT EXISTS ix_service_document_templates_service_id ON service_document_templates (service_id);
                ALTER TABLE service_document_templates ADD CONSTRAINT fk_service_document_templates_service_id
                    FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE CASCADE;
            END IF;
        END
        $$
    """)

    # Now drop the old service_id column from services
    op.execute('DROP INDEX IF EXISTS ix_services_service_id')
    op.execute('ALTER TABLE services DROP CONSTRAINT IF EXISTS uq_services_service_id')
    op.execute('ALTER TABLE services DROP COLUMN IF EXISTS service_id')
    
    # Recreate service_offices table with correct structure (numeric service_id)
    op.create_table('service_offices',
        sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column('service_name', sa.VARCHAR(length=255), nullable=False),
        sa.Column('service_id', sa.INTEGER(), nullable=False),
        sa.Column('office_name', sa.VARCHAR(length=255), nullable=False),
        sa.Column('address', sa.VARCHAR(length=500), nullable=False),
        sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), nullable=False),
        sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), nullable=False),
        sa.Column('working_hours', sa.VARCHAR(length=255), nullable=False),
        sa.Column('contact_email', sa.VARCHAR(length=255), nullable=False),
        sa.Column('notes', sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='fk_service_offices_service_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='service_offices_pkey')
    )
    op.create_index('ix_service_offices_id', 'service_offices', ['id'], unique=False)
    op.create_index('ix_service_offices_service_id', 'service_offices', ['service_id'], unique=False)
    op.create_index('ix_service_offices_service_name', 'service_offices', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('service_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('uq_services_service_id', 'services', ['service_id'])
    op.create_index('ix_services_service_id', 'services', ['service_id'], unique=False)
    op.drop_constraint(None, 'service_document_templates', type_='foreignkey')
    op.create_foreign_key('service_document_templates_service_id_fkey', 'service_document_templates', 'services', ['service_id'], ['service_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_service_document_templates_service_id'), table_name='service_document_templates')
    op.create_index('ix_service_document_templates_service_id', 'service_document_templates', ['service_id'], unique=False)
    op.create_unique_constraint('service_document_templates_service_id_key', 'service_document_templates', ['service_id'])
    op.alter_column('service_document_templates', 'service_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_table('service_offices',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('service_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('office_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('address', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('working_hours', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('contact_email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.service_id'], name='fk_service_offices_service_id_services', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='service_offices_pkey')
    )
    op.create_index('ix_service_offices_service_name', 'service_offices', ['service_name'], unique=False)
    op.create_index('ix_service_offices_service_id', 'service_offices', ['service_id'], unique=False)
    op.create_index('ix_service_offices_id', 'service_offices', ['id'], unique=False)
    # ### end Alembic commands ###
