"""create_service_offices_table

Revision ID: 756f6b364eb6
Revises: 20260428_0009
Create Date: 2026-05-08 16:23:12.996447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '756f6b364eb6'
down_revision: Union[str, None] = '20260428_0009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_offices',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('service_name', sa.String(length=255), nullable=False),
        sa.Column('service_id', sa.Integer(), nullable=False),
        sa.Column('office_name', sa.String(length=255), nullable=False),
        sa.Column('address', sa.String(length=500), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.Column('working_hours', sa.String(length=255), nullable=False),
        sa.Column('contact_email', sa.String(length=255), nullable=False),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['service_id'], ['services.id'], name='fk_service_offices_service_id', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id', name='service_offices_pkey')
    )
    op.create_index('ix_service_offices_id', 'service_offices', ['id'], unique=False)
    op.create_index('ix_service_offices_service_id', 'service_offices', ['service_id'], unique=False)
    op.create_index('ix_service_offices_service_name', 'service_offices', ['service_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_service_offices_service_name', table_name='service_offices')
    op.drop_index('ix_service_offices_service_id', table_name='service_offices')
    op.drop_index('ix_service_offices_id', table_name='service_offices')
    op.drop_table('service_offices')
    # ### end Alembic commands ###
